### ISSUE TITLE
FBX Export SOP

### ISSUE THREAD

**Issue by ivantitov-zd** [anvdev/Hammer-Tools#1]
- [x] Select geometry group to save
- [x] Split geometry by attribute

**Comment by ivantitov-zd** [comment]
Bugs (@nicolalifen)
- [x] An empty list of groups
- [x] Error on a bad file path
- [x] Confusion on implicitly adding an extension

**Comment by nicolalifen** [comment]
- [x] Support integer type with adding "_"prefix

**Comment by nicolalifen** [comment]
1. - Create 'Advanced' mode that include next params

- group
- grouptype
- take
- mkpath
- exportkind
- sdkversion
- polylod
- conversurfaces
- conservemem

2. - Bugs or features:

- Not realised "_"prefix for integer type attributes

- Realised "attribute name _ int" that looks more friendly

**Comment by ivantitov-zd** [comment]
> 1. * Create 'Advanced' mode that include next params
> 
> * group
> * grouptype
> * take
> * mkpath
> * exportkind
> * sdkversion
> * polylod
> * conversurfaces
> * conservemem
> 
> 1. * Bugs or features:
> 
> * Not realised "_"prefix for integer type attributes
> * Realised "attribute name _ int" that looks more friendly

Backlogged for the future.

**Comment by ivantitov-zd** [comment]
Toolbox
