### ISSUE TITLE
Group by Distance SOP

### ISSUE THREAD

**Issue by ivantitov-zd** [anvdev/Hammer-Tools#2]
Distance to:
- [x] Position
- [x] Plane
- [x] Geometry Point
- [x] Geometry Primitive
- [x] Geometry Surface
- [x] Geometry Bounding Box

**Comment by ivantitov-zd** [comment]
Waiting for #39

**Comment by anvdev** [comment]
Waiting for #38

**Comment by anvdev** [comment]
Switch doesn't work (expression missed)

**Comment by ivantitov-zd** [comment]
Toolbox
