### ISSUE TITLE
Poly Centroid SOP

### ISSUE THREAD

**Issue by ivantitov-zd** [anvdev/Hammer-Tools#39]
Methods:
- [x] Bounding Box
- [x] Average Position
- [x] Parametric UV
- [x] Edge-weighted
- [x] Area-weighted

**Comment by nicolalifen** [comment]
Area method is not stable

**Comment by ivantitov-zd** [comment]
Convex only (area-based)

**Comment by ivantitov-zd** [comment]
Toolbox
