### ISSUE TITLE
Group Invert SOP

### ISSUE THREAD

**Issue by ivantitov-zd** [anvdev/Hammer-Tools#5]
Aims
- [x] Fast invert group
- [x] Support vertex groups

**Comment by ivantitov-zd** [comment]
Fix it in future
- It is impossible to display a list of vertex groups in the menu at this moment
- For the same reason, it is not possible to detect that a group type is vertex

**Comment by nicolalifen** [comment]
- [x] Wrong menu type

**Comment by nicolalifen** [comment]
- [ ] Create 'Keep Original Group' flag (Group Promote style)
Enabled flag should activate 'New Name' field.
Default field value something like "`chs("group")`_inv"

**Comment by ivantitov-zd** [comment]
> * [ ]  Create 'Keep Original Group' flag (Group Promote style)
>   Enabled flag should activate 'New Name' field.
>   Default field value something like "`chs("group")`_inv"

Backlogged for the future.

**Comment by nicolalifen** [comment]
After selecting existing group, Group Invert SOP can create new group. For this feature change group type. Your new group will have some name, but new type.

**Comment by ivantitov-zd** [comment]
Toolbox

**Comment by ivantitov-zd** [comment]
Waiting for #76
