### ISSUE TITLE
Group Reverse SOP

### ISSUE THREAD

**Issue by ivantitov-zd** [anvdev/Hammer-Tools#6]
Source:
0 0 1 1 0 1
Target:
1 0 1 1 0 0

**Comment by ivantitov-zd** [comment]
Used @numelem instead of @numvtx due to a bug in 17.5.388

**Comment by ivantitov-zd** [comment]
> Used @numelem instead of @numvtx due to a bug in 17.5.388

The mistake in docs*

**Comment by nicolalifen** [comment]
- [x] Groups do not appear in group menu

**Comment by nicolalifen** [comment]
Realise "Bad pattern" warning. Group SOP style.

**Comment by ivantitov-zd** [comment]
Toolbox

**Comment by ivantitov-zd** [comment]
Waiting for #76
